site_name: notang

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
  font:
    text: Cascadia Code
    code: Cascadia Code
  palette:
    - scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

  - pymdownx.superfences
  - pymdownx.snippets

  - abbr

  - admonition
  - pymdownx.details

  - attr_list

  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite

  - pymdownx.tabbed:
      alternate_style: true

  - tables

  - footnotes

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - attr_list
  - md_in_html

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.betterem
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/theme.css